#!/bin/sh
DOT=${1:-~}
DOTFILES=$DOT/.dotfiles

cd $DOT
git clone ssh://git@github.com/feiz/.dotfiles.git && true

cat - > $DOTFILES/etc/environments << ENVFILE
DOT=$DOT
DOTFILES=$DOTFILES
ENVFILE

$DOTFILES/etc/deploy
